### ISSUE TITLE
user-service> com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by zhangwonderful** [PacktPublishing/Mastering-Microservices-with-Java#3]
Hi sourabhh,
    When I run the command "mvn docker:run" on the restaurant-service , errors show as below:
      user-service> 2017-03-30 10:06:41.030  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/747a86cc2f97:user-service:7770: registering service...
user-service> 2017-03-30 10:06:41.061 ERROR 1 --- [nfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error
user-service> 
user-service> com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
user-service> at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
user-service> at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar!/:1.19.1]
user-service> at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar!/:1.19.1]
user-service> at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar!/:1.19.1]
user-service> at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1]
user-service> at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.1.jar!/:1.19.1]
user-service> at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.register(AbstractJerseyEurekaHttpClient.java:56) ~[eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118) ~[eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79) ~[eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:815) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:104) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:88) [eureka-client-1.4.12.jar!/:1.4.12]
user-service> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
user-service> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
user-service> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
user-service> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_121]
user-service> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
user-service> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
user-service> at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
user-service> Caused by: java.net.ConnectException: Connection refused (Connection refused)
user-service> at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
user-service> at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
user-service> at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
user-service> at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
user-service> at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
user-service> at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
user-service> at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]
user-service> at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
user-service> ... 30 common frames omitted

Would you please kindly help me how to resolve this issu?

**Comment by zhangwonderful** [comment]
Sorry ,  I run the command "mvn docker:run" on the user-service , errors show as above.

**Comment by zhangwonderful** [comment]
another error:
user-service> 2017-03-30 11:53:21.920  INFO 1 --- [OXeF9trGJiSA-21] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@64a04814: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
user-service> 2017-03-30 11:53:26.929  WARN 1 --- [OXeF9trGJiSA-22] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)

In fact, my rabbitmq runs normally,5672 and 15672 port can be accessed. But system always throws exception : org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused

**Comment by sharmasourabh** [comment]
It seems connection issue with Discovery and RabbitMQ server. I believe you have not made any change in code after cloning. I'll test during this weekend and get back to you.

**Comment by sharmasourabh** [comment]
Hi zhangwonderful,

I just checked and found out following findings:

If you see docker example was given to demonstrate how you could create docker images and run it with maven and docker-compose. Therefore, if you see the application.yml, you would find the following entry for eureka under docker spring profile:
```
serviceUrl:
      defaultZone: http://eureka:8761/eureka/
```
As you can see in above entry it refers to host eureka in URL. So when you run only single image of service (using mvn docker:start) it won't find eureka in running container.
Now to make it work, you need to use docker-compose. docker-compose.yml is there in project root folder. In docker-compose.yml we have defined the eureka service and linked it with service like restaurant, user or any other.
Therefore, now when you run docker-compose you won't find discovery exceptions.

Similarly, when you would add the RabbitMQ service entry in docker-compose and update the main app class like (RestaurantApp or UsersApp) and just make sure it points to the RabbitMQ defined in docker-compose.yml. (Following line presently points to localhost). This should resolve the RabbitMQ exceptions.
```
    @Value("${app.rabbitmq.host:localhost}")
    String rabbitMqHost;
```
Above changes should work. Let me know if you still face issue.

**Comment by zhangwonderful** [comment]
Thank Sourabh  for your response.
    When I change the configuration  defaultZone: http://eureka:8761/eureka/  into http://192.168.10.88:8761/eureka/, it doesnt't work even if I run eureka server firstly. But when I add configuration in /etc/hosts as 192.168.10.88 eureka, and remains the defaultZone configuration as you mentioned http://eureka:8761/eureka/ , the user-service registers eureka server successfully. I don't know why it works when I add the hostname into /etc/hosts. 
    But user-service system still throws exception : org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused  which shows it can't interconnect with rabbitmq server even if rabbitmq server works normally. 
   The solution is only to use docker-compse , and no other solution?

**Comment by sharmasourabh** [comment]
Glad, one issue is resolved.

When you run the container it only contains the JRE environment with service. This container does not contain the RabbitMQ, therefore it throws the error as it points to localhost.

Now in current context, either you can first build a base image (currently only jre) that contains both jre and RabbitMQ and then use this new image in service docker file. Then RabbitMQ would be available on localhost internally.

Another way is obviously Docker Compose which is more relevant and proper. Because if we are having multiple service, we should have central RabbitMQ and other such services like Discovery, API gateway etc.

Also, you can explore the clustering using kubernetes which is now widely used on production systems.
