### ISSUE TITLE
angularjs code is not complete

### ISSUE THREAD

**Issue by zhangwonderful** [PacktPublishing/Mastering-Microservices-with-Java#4]
Hi sourabhh,
    When run "npm start" for the OTRS_UI project, there are many errors due to missing many files as below:
  <script type="text/javascript" src="scripts/templates.js"></script>
         <script type="text/javascript" src="scripts/httperror/httperror.js"></script>
        <script type="text/javascript" src="scripts/login/login.js"></script>
        <script type="text/javascript" src="scripts/restaurants/restaurants.js"></script>
    app/src/styles/application.css 

other erros :
Uncaught TypeError: b.module(...).info is not a function
    at angular-resource.js:436
    at angular-resource.js:6

**Comment by sharmasourabh** [comment]
Hi zhangwonderful,

Could you please share following information? Have you clone the repo or setup your own? Which node and npm version, you are using?

This type of error comes when install is not done properly.

If you have the command log, could you please ping the set of commands you have executed?

PS: Few days back, I tested the code with node 6.9.1 and npm 3.10.8.

**Comment by zhangwonderful** [comment]
Hi sourabhh,
   I got the repo by the command of git clone https://github.com/PacktPublishing/Mastering-Microservices-with-Java.git . My OS is centos 7.3 64bit, node version is 6.9.5. I

**Comment by sharmasourabh** [comment]
I have only tested it on Windows platform. But, ideally that should not be the problem.

Could you please send me the commands you fired and its output after cloning. This would help me to find out if there is any issue in install or configuration.

Thanks.
