### ISSUE TITLE
Is there a multi-thread problem in MDCConcurrentCallable.java?

### ISSUE THREAD

**Issue by salaha0** [PacktPublishing/Mastering-Microservices-with-Java#6]
public K call() throws Exception {
        LOG.debug("Call using MDCHystrixContextCallable...");
        Map childMDC = MDC.getCopyOfContextMap();
        LOG.debug("childMDC --> " + childMDC);
        try {
            if (parentMDC != null) {
                **MDC.setContextMap(parentMDC);**
            }
            LOG.debug("parentMDC --> " + parentMDC);
            return actual.call();
        } finally {
            if (childMDC != null) {
                **MDC.setContextMap(childMDC);**
            }
        }
    }

**Comment by sharmasourabh** [comment]
> ### This repo contains code of 1st edition.

### You may want to explore 3rd edition;

- Code: [Mastering Microservices with Java - 3rd Edition](https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition)
- Book: [Mastering Microservices with Java: Build enterprise microservices with Spring Boot 2.0, Spring Cloud, and Angular, 3rd Edition](https://amzn.to/2VW3UyU)
